import type { Metadata } from 'next'

export type AICountryData = {
  slug: string
  country: string
  locale: string
  audience: string
  context: string
  situations: string[]
  keywords: string[]
}

export const AI_COUNTRIES: Record<string, AICountryData> = {
  usa: { slug: 'usa', country: 'USA', locale: 'en-US', audience: 'Indians and South Asians living in the United States', context: 'For people living in the USA, an AI conversation can be useful but may not be what you want when the real need is to talk with another person. LeanOn offers human peer conversations for homesickness, relationship pressure, work stress, cultural adjustment and everyday loneliness.', situations: ['Missing family in India across a large time-zone gap', 'Work, relocation or immigration-related stress', 'Dating, marriage and family expectations across cultures', 'Feeling isolated even when work and social life look busy'], keywords: ['ChatGPT alternative USA Indian', 'talk to a real person USA', 'Indian emotional support USA', 'human listener USA', 'AI companion alternative USA'] },
  canada: { slug: 'canada', country: 'Canada', locale: 'en-CA', audience: 'Indians and South Asians living in Canada', context: 'Moving to Canada can change your social circle, routines and relationship with family back home. LeanOn is an option when you want a real person to listen rather than another AI-generated conversation.', situations: ['Homesickness and distance from parents', 'Immigration, study or work pressure', 'Adjusting to a new city or social circle', 'Relationship and marriage conversations that are hard to have with family'], keywords: ['ChatGPT alternative Canada Indian', 'talk to a real person Canada', 'Indian emotional support Canada', 'human listener Canada', 'AI companion alternative Canada'] },
  uk: { slug: 'uk', country: 'UK', locale: 'en-GB', audience: 'Indians and South Asians living in the United Kingdom', context: 'For British Indians and newer Indian migrants, AI can be useful for reflection and information. LeanOn is different: it provides a one-to-one conversation with a real peer listener when you want human connection and cultural context.', situations: ['Feeling between Indian and British expectations', 'Homesickness, festivals and family distance', 'Work or relocation pressure', 'Relationship and marriage conversations'], keywords: ['ChatGPT alternative UK Indian', 'talk to a real person UK', 'Indian emotional support UK', 'British Indian peer support', 'AI companion alternative UK'] },
  uae: { slug: 'uae', country: 'UAE', locale: 'en-AE', audience: 'Indians and South Asians living in the United Arab Emirates', context: 'Expatriate life in the UAE can be busy while still leaving little room for honest conversations. LeanOn is an option when you specifically want another human being to listen about work, relationships, family back home or loneliness.', situations: ['Expatriate work pressure', 'Missing family and friends in India', 'Relationship or marriage pressure', 'Needing a private conversation after a difficult day'], keywords: ['ChatGPT alternative UAE Indian', 'talk to a real person Dubai', 'Indian emotional support UAE', 'human listener Dubai', 'AI companion alternative UAE'] },
  singapore: { slug: 'singapore', country: 'Singapore', locale: 'en-SG', audience: 'Indians and South Asians living in Singapore', context: 'Singapore life can be highly connected and still feel emotionally private. If an AI conversation is not the kind of connection you want, LeanOn provides one-to-one conversations with real peer listeners.', situations: ['Work intensity and career pressure', 'Relocation and homesickness', 'Relationship or marriage uncertainty', 'Wanting to talk without involving your existing social circle'], keywords: ['ChatGPT alternative Singapore Indian', 'talk to a real person Singapore', 'Indian emotional support Singapore', 'human listener Singapore', 'AI companion alternative Singapore'] },
  malaysia: { slug: 'malaysia', country: 'Malaysia', locale: 'en-MY', audience: 'Indians and South Asians living in Malaysia', context: 'For Indians and South Asians in Malaysia, a human conversation can be useful when the need is not information but simply having another person listen. LeanOn supports text and voice peer conversations.', situations: ['Family expectations and difficult conversations', 'Work or study pressure', 'Relationship and marriage concerns', 'Feeling disconnected or needing a neutral listener'], keywords: ['ChatGPT alternative Malaysia Indian', 'talk to a real person Malaysia', 'Indian emotional support Malaysia', 'human listener Malaysia', 'AI companion alternative Malaysia'] },
  kuwait: { slug: 'kuwait', country: 'Kuwait', locale: 'en-KW', audience: 'Indians and South Asians living in Kuwait', context: 'For expatriates in Kuwait, work schedules and distance from family can make it hard to find someone to talk to. LeanOn is an option when you want a real human conversation rather than an AI response.', situations: ['Shift work and expatriate pressure', 'Homesickness and family distance', 'Marriage or relationship pressure', 'Needing someone neutral to listen'], keywords: ['ChatGPT alternative Kuwait Indian', 'talk to a real person Kuwait', 'Indian emotional support Kuwait', 'human listener Kuwait', 'AI companion alternative Kuwait'] },
  oman: { slug: 'oman', country: 'Oman', locale: 'en-OM', audience: 'Indians and South Asians living in Oman', context: 'Living abroad can make ordinary emotional conversations harder to start. LeanOn gives Indians and South Asians in Oman an option for a real peer conversation about work, homesickness, relationships and family pressure.', situations: ['Long workdays or expatriate pressure', 'Missing family in India', 'Relationship and marriage concerns', 'Feeling isolated despite living around other people'], keywords: ['ChatGPT alternative Oman Indian', 'talk to a real person Oman', 'Indian emotional support Oman', 'human listener Oman', 'AI companion alternative Oman'] },
  australia: { slug: 'australia', country: 'Australia', locale: 'en-AU', audience: 'Indians and South Asians living in Australia', context: 'For Indians in Australia, AI can be useful for information and reflection. LeanOn is an option when you specifically want human connection — a real listener for homesickness, study, work, relationships and everyday pressure.', situations: ['University or work pressure', 'Homesickness and family distance', 'Long-distance relationship concerns', 'Cultural adjustment after moving abroad'], keywords: ['ChatGPT alternative Australia Indian', 'talk to a real person Australia', 'Indian emotional support Australia', 'human listener Australia', 'AI companion alternative Australia'] },
}

export function buildAICountryMetadata(data: AICountryData): Metadata {
  return {
    title: `ChatGPT Alternative for Indians in ${data.country} — Talk to a Real Person | LeanOn`,
    description: `Want a real person instead of an AI conversation in ${data.country}? LeanOn connects Indians and South Asians with real peer listeners by text or voice.`,
    keywords: data.keywords,
    alternates: { canonical: `https://www.leanon.app/ai-chatbot-alternative-${data.slug}`, languages: { [data.locale]: `https://www.leanon.app/ai-chatbot-alternative-${data.slug}` } },
    openGraph: { title: `Talk to a Real Person Instead of AI in ${data.country} | LeanOn`, description: `AI can be useful. LeanOn is for Indians and South Asians in ${data.country} who specifically want a real human conversation.`, url: `https://www.leanon.app/ai-chatbot-alternative-${data.slug}`, siteName: 'LeanOn', type: 'website' },
  }
}

export default function AICountryPage({ data }: { data: AICountryData }) {
  const url = `https://www.leanon.app/ai-chatbot-alternative-${data.slug}`
  const faqs = [
    { q: `Can Indians in ${data.country} talk to a real person instead of ChatGPT?`, a: `Yes. LeanOn connects seekers with real human peer listeners for one-to-one conversations by text or voice. Live listener availability is shown in the app.` },
    { q: 'Is LeanOn an AI chatbot?', a: 'No. LeanOn provides human peer conversations. The person on the other side of the conversation is a real listener.' },
    { q: 'Is AI bad for emotional support?', a: 'Not necessarily. AI assistants can be useful for information, reflection and many other purposes. LeanOn serves a different need: human-to-human conversation when that is what the user wants.' },
    { q: 'Can I try LeanOn before paying?', a: 'New seekers can start with one free 5-minute introductory session. If you continue, the listener rate is shown before starting a paid conversation.' },
    { q: 'Is LeanOn therapy?', a: 'No. LeanOn provides peer support and human connection, not therapy, counselling, diagnosis or clinical treatment.' },
  ]
  const jsonLd = { '@context': 'https://schema.org', '@graph': [
    { '@type': 'WebPage', name: `ChatGPT Alternative for Indians in ${data.country}`, description: data.context, url },
    { '@type': 'FAQPage', mainEntity: faqs.map(f => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })) },
    { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'LeanOn', item: 'https://www.leanon.app' }, { '@type': 'ListItem', position: 2, name: `AI Alternative ${data.country}`, item: url }] },
  ] }

  return <main className="min-h-screen bg-white text-[#0F4867]">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <div className="mx-auto max-w-4xl px-5 py-8 sm:px-8 sm:py-12">
      <nav className="mb-12 flex items-center justify-between"><a href="/" className="text-2xl font-black">Lean<span className="text-[#1A8FA0]">On</span></a><a href="/browse" className="rounded-full bg-[#1A8FA0] px-5 py-2.5 text-sm font-extrabold text-white">Browse listeners</a></nav>
      <header className="max-w-3xl"><p className="mb-4 text-sm font-extrabold uppercase tracking-widest text-[#1A8FA0]">Human connection · {data.country}</p><h1 className="mb-6 text-4xl font-black leading-tight sm:text-6xl">Want to talk to a <span className="text-[#FF9933]">real person</span> instead of AI in {data.country}?</h1><p className="mb-8 text-lg leading-8 text-slate-600">{data.context}</p><a href="/browse" className="inline-flex rounded-full bg-[#FF9933] px-7 py-3.5 font-extrabold text-white">Talk to a real listener →</a></header>
      <section className="mt-12 rounded-3xl border border-[#D5EEF6] bg-[#F0F8FC] p-6 sm:p-8"><h2 className="mb-4 text-2xl font-black">Who this is for</h2><p className="leading-7 text-slate-600">{data.audience}. You might already use ChatGPT, Gemini or another AI assistant and still want something different: another human being who can listen.</p><ul className="mt-5 grid gap-3 sm:grid-cols-2">{data.situations.map(s => <li key={s} className="rounded-2xl bg-white p-4 text-slate-700">{s}</li>)}</ul></section>
      <section className="mt-8 rounded-3xl border border-slate-200 p-6 sm:p-8"><h2 className="mb-4 text-2xl font-black">AI conversation or human conversation?</h2><div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-5"><h3 className="font-black">AI assistants</h3><p className="mt-2 leading-7 text-slate-600">Useful for information, brainstorming, reflection and an AI-generated conversation.</p></div><div className="rounded-2xl bg-slate-50 p-5"><h3 className="font-black">LeanOn</h3><p className="mt-2 leading-7 text-slate-600">For people who specifically want a real human peer conversation by text or voice.</p></div></div></section>
      <section className="mt-8 rounded-3xl bg-[#0F4867] p-7 text-white"><h2 className="mb-3 text-2xl font-black">Try a real human conversation</h2><p className="leading-7 text-white/85">New seekers can start with one free 5-minute introductory session. Continue only if the conversation feels useful; the listener rate is shown before a paid session.</p><a href="/browse" className="mt-6 inline-flex rounded-full bg-[#FF9933] px-7 py-3.5 font-extrabold text-white">Find a listener →</a></section>
      <section className="mt-10"><h2 className="mb-4 text-2xl font-black">Questions people ask</h2><div className="divide-y divide-slate-200 rounded-2xl border border-slate-200 px-5">{faqs.map(f => <details key={f.q} className="py-4"><summary className="cursor-pointer font-extrabold">{f.q}</summary><p className="pt-3 leading-7 text-slate-600">{f.a}</p></details>)}</div></section>
      <p className="mt-10 text-xs leading-6 text-slate-500">LeanOn provides peer support and human connection, not therapy, counselling, diagnosis or clinical treatment. If you are in immediate danger or experiencing a mental-health emergency, contact an appropriate local emergency or crisis service.</p>
    </div>
  </main>
}
