import { MetadataRoute } from 'next'
import { RESOURCES } from '@/lib/resources-data'
import { FEELINGS } from '@/lib/feelings-data'

export const dynamic = 'force-static'

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://www.leanon.app'
  const d = (s: string) => new Date(s)
  // The sitemap is force-static, so this evaluates at BUILD time — i.e. the
  // deploy date. Using the build date instead of a hardcoded string means the
  // "fresh" pages' lastModified never silently goes stale between deploys.
  const TODAY = new Date().toISOString().slice(0, 10)
  return [
    { url: base,                                       lastModified: d(TODAY),        changeFrequency: 'daily',   priority: 1.0 },
    { url: `${base}/browse`,                           lastModified: d(TODAY),        changeFrequency: 'hourly',  priority: 0.95 },
    { url: `${base}/about`,                            lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/become-listener`,                  lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/contact`,                          lastModified: d('2026-01-01'), changeFrequency: 'yearly',  priority: 0.5 },
    { url: `${base}/faq`,                              lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/glossary`,                         lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/privacy`,                          lastModified: d('2026-01-01'), changeFrequency: 'yearly',  priority: 0.3 },
    { url: `${base}/terms`,                            lastModified: d('2026-01-01'), changeFrequency: 'yearly',  priority: 0.3 },
    { url: `${base}/trust`,                            lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/press`,                            lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.6 },
    // Support hub + topic pages
    { url: `${base}/support`,                          lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/support/loneliness`,               lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/support/anxiety`,                  lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/support/breakup`,                  lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/support/grief`,                    lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/support/founder-burnout`,          lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/support/student-stress`,           lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/support/career-confusion`,         lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/support/relationship-stress`,      lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/support/emotional-support`,        lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/support/someone-to-talk-to`,       lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/support/anonymous-support`,        lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/support/social-anxiety`,            lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/support/imposter-syndrome`,         lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/support/work-from-home-loneliness`, lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.85 },
    // Seeker-intent support pages (Round 4 — acquiring paying users, not listeners)
    { url: `${base}/support/overthinking`,             lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/support/marriage-loneliness`,      lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/support/job-loss`,                 lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/support/sunday-night-loneliness`,  lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/support/long-distance-relationship`, lastModified: d(TODAY),      changeFrequency: 'monthly', priority: 0.85 },
    // Blog
    { url: `${base}/blog`,                             lastModified: d('2026-05-01'), changeFrequency: 'weekly',  priority: 0.75 },
    { url: `${base}/blog/loneliness-in-india`,         lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/blog/burnout-recovery-india`,      lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/blog/how-peer-support-works`,      lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/blog/what-does-lean-on-mean`,      lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/blog/loneliness-at-night`,         lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/blog/emotional-burnout`,           lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/blog/anonymous-emotional-support-india`, lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/blog/peer-support-vs-therapy-india`,              lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/blog/joint-family-emotional-support`,             lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/blog/how-to-deal-with-loneliness-in-joint-family-india`, lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/blog/startup-founder-burnout-stories-and-recovery`, lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/blog/affordable-alternatives-to-therapy-in-india`, lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/blog/mens-mental-health-talking-is-strength`,      lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/blog/women-loneliness-india-peer-support`,         lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/blog/empathy-in-peer-support`,                     lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/blog/what-is-peer-support-india`,                  lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/blog/online-emotional-support-india-guide`,        lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/blog/how-to-stop-overthinking-at-night`,           lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/blog/no-one-to-talk-to`,                           lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/blog/therapy-cost-india`,                          lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/blog/why-people-call-astrologers-to-talk`,         lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/blog/what-it-means-to-have-someone-to-lean-on`,    lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/blog/paid-friend-vs-peer-support-india`, lastModified: d('2026-09-12'), changeFrequency: 'monthly', priority: 0.9 },
    // Brand + authority pages
    { url: `${base}/leanon`,                           lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/emotional-support`,                lastModified: d('2026-04-01'), changeFrequency: 'monthly', priority: 0.9 },
    // Long-tail SEO pages
    { url: `${base}/leanon-app-mental-health`,         lastModified: d('2026-05-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/anonymous-peer-support`,           lastModified: d('2026-05-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/need-someone-to-talk-to-india`,    lastModified: d('2026-05-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/get-paid-to-chat-india`,           lastModified: d('2026-05-01'), changeFrequency: 'monthly', priority: 0.8 },
    // High-commercial-intent seeker pages (Round 4). Priority 0.95 — these are
    // the pages that reach people ready to PAY, which is the current bottleneck.
    { url: `${base}/online-counselling-india-cost`,    lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/talk-to-someone-right-now`,        lastModified: d(TODAY),        changeFrequency: 'weekly',  priority: 0.95 },
    // Astrology-chat bridge — intercepts searchers already turning to
    // astrology apps for a conversation, not a prediction (see PROJECT.md §2).
    { url: `${base}/talk-to-someone-not-astrologer`,   lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    // "lean on" (with a space) cluster — the head term is owned by the 2015
    // Major Lazer song, so this targets the emotional-intent long tail instead.
    { url: `${base}/someone-to-lean-on`,               lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    // Daily check-in hub + mood pages — the recurring-entry-point engine.
    { url: `${base}/daily-check-in`,                   lastModified: d(TODAY),        changeFrequency: 'daily',   priority: 0.9 },
    ...FEELINGS.map(f => ({
      url: `${base}/feeling/${f.slug}`,
      lastModified: d(TODAY),
      changeFrequency: 'weekly' as const,
      priority: 0.85,
    })),
    // City pages
    { url: `${base}/bengaluru`,                        lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/mumbai`,                           lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/delhi`,                            lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/hyderabad`,                        lastModified: d('2026-03-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/chennai`,                          lastModified: d('2026-06-11'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/pune`,                             lastModified: d('2026-06-11'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/kolkata`,                          lastModified: d('2026-06-11'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/jaipur`,                           lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/ahmedabad`,                        lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.8 },
    // AI/ChatGPT-alternative + earning pages — the highest-growth SEO cluster
    { url: `${base}/chat-with-real-person`,            lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/ai-chatbot-alternative`,           lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/ai-human-support`,              lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/earn-by-listening`,                lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    // High-intent immediate-need landing page
    { url: `${base}/i-need-someone-to-talk-to`,        lastModified: d(TODAY),        changeFrequency: 'weekly',  priority: 0.97 },
    // New support topic pages
    { url: `${base}/support/feeling-empty`,            lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/support/feeling-like-a-failure`,   lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/support/cant-sleep-anxiety`,       lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/support/need-to-vent`,             lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/support/emotional-exhaustion`,     lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/support/feeling-lost`,             lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    // Blog: AI vs human + earning posts
    { url: `${base}/blog/chatgpt-vs-human-listener`,   lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/blog/earn-money-listening-online-india`, lastModified: d(TODAY),  changeFrequency: 'monthly', priority: 0.9 },
    // Blog: ChatGPT-user + high-intent emotional queries
    { url: `${base}/blog/is-chatgpt-good-for-mental-health`, lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.92 },
    { url: `${base}/blog/feel-empty-inside-india`,     lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/blog/feel-like-a-failure-india`,   lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/blog/2am-loneliness-india`,        lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/blog/hate-job-cant-quit-india`,    lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.9 },
    // Blog: vent/impulse persona — daytime, situational-trigger, pressure-valve
    { url: `${base}/blog/getting-it-off-your-chest`,         lastModified: d(TODAY),  changeFrequency: 'monthly', priority: 0.92 },
    { url: `${base}/blog/bad-morning-reset-india`,           lastModified: d(TODAY),  changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/blog/venting-to-a-stranger-india`,       lastModified: d(TODAY),  changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/blog/emotional-reset-workday-india`,     lastModified: d(TODAY),  changeFrequency: 'monthly', priority: 0.9 },
    // Vent/impulse landing pages — highest-converting persona (daytime, one-session, acute trigger)
    { url: `${base}/need-to-vent-right-now`,           lastModified: d(TODAY),        changeFrequency: 'weekly',  priority: 0.97 },
    { url: `${base}/vent-to-someone-online`,           lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/having-a-bad-day`,                 lastModified: d(TODAY),        changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/just-had-a-fight`,                 lastModified: d(TODAY),        changeFrequency: 'weekly',  priority: 0.93 },
    { url: `${base}/talk-to-stranger-online-india`,    lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.93 },
    // Seeker acquisition — high-commercial-intent pages targeting people who WANT support
    // (not listeners). Addresses the listener-heavy supply/demand imbalance.
    { url: `${base}/online-counseling-india`,            lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/cant-afford-therapy-india`,          lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/support/family-pressure-india`,      lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/support/career-pressure-india`,      lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/support/new-city-india`,             lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.93 },
    { url: `${base}/support/relationship-anxiety`,       lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.93 },
    { url: `${base}/support/arranged-marriage-stress`,   lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.93 },
    { url: `${base}/support/postpartum-india`,           lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.93 },
    // Blog: seeker-acquisition posts (therapy cost, family pressure, new city, signs)
    { url: `${base}/blog/cant-afford-therapy-india`,     lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/blog/family-pressure-mental-health-india`, lastModified: d(TODAY),  changeFrequency: 'monthly', priority: 0.93 },
    { url: `${base}/blog/loneliness-new-city-india`,     lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.92 },
    { url: `${base}/blog/signs-you-need-to-talk-to-someone`, lastModified: d(TODAY),    changeFrequency: 'monthly', priority: 0.92 },
    // Women-targeting hub + seeker pages — Avantikka-cluster (married women, mothers, working women)
    // Both paid sessions to date are women 20s-30s → dedicated women's SEO cluster
    { url: `${base}/for-women`,                           lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/support/married-but-lonely`,          lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/support/mom-burnout-india`,           lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/support/working-woman-india`,         lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/support/husband-not-supportive-india`, lastModified: d(TODAY),       changeFrequency: 'monthly', priority: 0.95 },
    // Blog: women-cluster posts
    { url: `${base}/blog/married-but-lonely-india`,       lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/blog/working-mothers-mental-health-india`, lastModified: d(TODAY),   changeFrequency: 'monthly', priority: 0.93 },
    { url: `${base}/blog/mom-burnout-signs-india`,        lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.93 },
    // Harshit-cluster pages — men's loneliness, marriage pressure, fear of marriage, adulting, banking stress
    // First male paid user: bank employee, lonely, job+marriage pressure, parents who cheated on each other
    { url: `${base}/support/men-loneliness-india`,        lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/support/not-ready-to-get-married-india`, lastModified: d(TODAY),     changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/support/fear-of-marriage-india`,      lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/support/adulting-india`,              lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/support/banking-job-stress-india`,    lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    // Blog: Harshit-cluster posts
    { url: `${base}/blog/men-loneliness-india`,           lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/blog/fear-of-marriage-india`,         lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.93 },
    { url: `${base}/blog/adulting-loneliness-india`,      lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.93 },
    // Sakshi-cluster pages — emotional numbness, morning dread, childhood trauma, professional help access
    { url: `${base}/support/emotional-numbness`,          lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/support/dont-want-to-get-out-of-bed`, lastModified: d(TODAY),       changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/support/childhood-trauma-india`,      lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.93 },
    { url: `${base}/i-need-professional-help-india`,      lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    // New SEO pages (Items 18-21)
    { url: `${base}/why-leanon`,                       lastModified: d('2026-05-01'), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/how-leanon-works`,                 lastModified: d('2026-05-01'), changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/is-leanon-safe`,                   lastModified: d('2026-05-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/anonymous-support-online`,         lastModified: d('2026-05-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/someone-to-talk-to-at-night`,      lastModified: d('2026-05-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/online-emotional-support-india`,   lastModified: d('2026-05-01'), changeFrequency: 'monthly', priority: 0.9 },
    // AstroTalk-overlap + relationship + loneliness cluster
    { url: `${base}/astrotalk-alternative`,            lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/relationship-advice-online-india`, lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/talk-to-real-person-online-india`, lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/loneliness-support-india`,         lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/alternatives-to-therapy-india`,    lastModified: d('2026-05-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/feeling-lonely-in-india`,          lastModified: d('2026-05-01'), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/our-story`,                        lastModified: d('2026-05-01'), changeFrequency: 'monthly', priority: 0.8 },
    // Competitor-alternative pages — intercepts high-intent searchers who already
    // know a competing product and are looking for something better
    { url: `${base}/yourdost-alternative`,             lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/wysa-alternative`,                 lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    // Condition / emotion landing pages — some of the highest-volume mental-health
    // searches in India; positioned as peer support, not clinical treatment
    { url: `${base}/depression-support-india`,         lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/feeling-overwhelmed-india`,        lastModified: d(TODAY),        changeFrequency: 'weekly',  priority: 0.95 },
    // Natural-language seeker queries — typed before the person knows the
    // clinical vocabulary; often the first touchpoint in the funnel
    { url: `${base}/talk-about-my-problems-online`,    lastModified: d(TODAY),        changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/peer-support-online-india`,        lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    // Peer support keyword cluster (Round 8) — "peer support" has no LeanOn
    // result on Google; highest-priority SEO gap. Also targets AI citation.
    { url: `${base}/peer-support`,                     lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/peer-counselling-india`,           lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/mental-health-support-india`,      lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/best-peer-support-app-india`,      lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    // AstroTalk competition cluster — intercepts searchers using astrology apps
    // for emotional support (love/marriage/relationship problems, late-night chat,
    // pay-per-minute chat). AstroTalk's top keywords reframed as peer support.
    { url: `${base}/pay-to-talk-online-india`,         lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/love-problems-india`,              lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/marriage-problems-india`,          lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/anonymous-chat-india`,             lastModified: d(TODAY),        changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/late-night-support-india`,         lastModified: d(TODAY),        changeFrequency: 'weekly',  priority: 0.97 },
    // Blog: AstroTalk comparison posts
    { url: `${base}/blog/astrotalk-expensive-alternative`,      lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.93 },
    { url: `${base}/blog/talk-to-real-person-not-astrologer`,   lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.93 },
    // Round 8: peer support keyword cluster blog posts
    { url: `${base}/blog/best-peer-support-apps-india-2026`,   lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/blog/peer-counselling-india-guide`,         lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/blog/mental-health-support-cost-india`,     lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    // Round 9: 15 landing pages — paid counselling, app comparisons, topic clusters, city pages
    { url: `${base}/paid-counselling-india`,            lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/relationship-counselling-india`,    lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/betterhelp-alternative-india`,      lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/innerhour-alternative`,             lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/empathy-friend-india`,              lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/stress-management-india`,           lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/work-stress-india`,                 lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/trauma-support-india`,              lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/anger-management-india`,            lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/men-mental-health-india`,           lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/nri-mental-health`,                 lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/teen-mental-health-india`,          lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/best-mental-health-app-india`,      lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/emotional-wellness-india`,          lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/online-support-group-india`,        lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    // Round 9: 4 city pages
    { url: `${base}/noida`,                             lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/gurgaon`,                           lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/chandigarh`,                        lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/kochi`,                             lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.85 },
    // Round 10: relationship & moment-specific landing pages
    { url: `${base}/vent-about-relationship-india`,         lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/relationship-frustration-india`,        lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/partner-not-understanding-india`,       lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/morning-emotional-support-india`,       lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/after-fight-with-partner-india`,        lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/talk-during-commute-india`,             lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/relationship-advice-vs-venting-india`,  lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    // Round 10: 3 blog posts
    { url: `${base}/blog/morning-fight-with-partner-india`,    lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.93 },
    { url: `${base}/blog/venting-relationship-india`,          lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.93 },
    { url: `${base}/blog/talk-to-someone-workday-india`,       lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.93 },
    // Round 11: 20 landing pages — emotional support verticals, city pages
    { url: `${base}/empathy-india`,                   lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/paid-friend-india`,               lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/online-friend-india`,             lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/stranger-friend-india`,           lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/someone-who-gets-it-india`,       lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/rant-online-india`,               lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/get-it-off-your-chest-india`,     lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/tarot-alternative-india`,         lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/astroyogi-alternative`,           lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/talk-therapy-india`,              lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/walk-in-counselling-india`,       lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/quarter-life-crisis-india`,       lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/midlife-crisis-india`,            lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/existential-crisis-india`,        lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/housewife-support-india`,         lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/single-parent-india`,             lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/divorce-support-india`,           lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/interfaith-relationship-india`,   lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/cant-tell-anyone-india`,          lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/doctor-burnout-india`,            lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.97 },
    // Round 11: 5 city pages
    { url: `${base}/lucknow`,                         lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/surat`,                           lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/nagpur`,                          lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/bhopal`,                          lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/visakhapatnam`,                   lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.85 },
    // Round 11: 8 blog posts
    { url: `${base}/blog/empathy-meaning-india`,                    lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/blog/paid-friend-vs-peer-support-india`,        lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/blog/quarter-life-crisis-india-guide`,          lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/blog/tarot-astrology-emotional-support-india`,  lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/blog/housewife-mental-health-india-guide`,      lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/blog/divorce-india-emotional-recovery`,         lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/blog/stranger-conversation-healing-india`,      lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/blog/rant-vs-vent-india`,                       lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    // Round 9: 5 blog posts
    { url: `${base}/blog/best-mental-health-apps-india-2026`,             lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/blog/it-burnout-india-how-to-cope`,                   lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.93 },
    { url: `${base}/blog/nri-mental-health-india-guide`,                  lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.93 },
    { url: `${base}/blog/relationship-counselling-vs-peer-support-india`, lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.93 },
    { url: `${base}/blog/how-to-find-anger-management-support-india`,     lastModified: d(TODAY), changeFrequency: 'monthly', priority: 0.93 },
    // Resources hub + all resource pages
    // NOTE: `loneliness-statistics-india` is intentionally NOT hardcoded here —
    // it lives in RESOURCES (resources-data.ts), so the .map below already emits
    // it. Listing it above too put it in the sitemap twice.
    { url: `${base}/resources`,                        lastModified: d('2026-05-01'), changeFrequency: 'monthly', priority: 0.8 },
    ...RESOURCES.map(r => ({
      url: `${base}/resources/${r.slug}`,
      lastModified: d('2026-05-01'),
      changeFrequency: 'monthly' as const,
      priority: 0.75,
    })),
    // Round 12 — 35 high-intent paying-user keyword pages (2026-09-13)
    { url: `${base}/cheating-partner-india`,                   lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/mother-in-law-stress-india`,               lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/toxic-relationship-india`,                 lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/emotional-abuse-india`,                    lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/affair-recovery-india`,                    lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/feeling-trapped-india`,                    lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/heartbreak-india`,                         lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/overthinking-relationship-india`,          lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/controlling-relationship-india`,           lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/gaslighting-india`,                        lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/financial-anxiety-india`,                  lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/job-loss-support-india`,                   lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/upsc-stress-india`,                        lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/competitive-exam-stress-india`,            lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/anxiety-attack-india`,                     lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/crying-for-no-reason-india`,               lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/no-motivation-india`,                      lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/feeling-empty-inside-india`,               lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/panic-attack-india`,                       lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/people-pleaser-india`,                     lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/low-self-esteem-india`,                    lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/social-anxiety-india`,                     lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/imposter-syndrome-india`,                  lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/joint-family-stress-india`,                lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/parents-forcing-marriage-india`,           lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/sasural-problems-india`,                   lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/bad-day-india`,                            lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/need-to-vent-india`,                       lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/emotional-support-india`,                  lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/talk-to-someone-free-india`,               lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/working-woman-stress-india`,               lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/new-mom-india`,                            lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/relationship-trust-issues-india`,          lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/communication-problems-relationship-india`, lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    { url: `${base}/feeling-invisible-india`,                  lastModified: d('2026-09-13'), changeFrequency: 'monthly', priority: 0.97 },
    // Round 13: NRI, diaspora, and global emotional support pages (2026-09-13)
    { url: `${base}/nri-support`,                lastModified: d('2026-09-13'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indian-diaspora-support`,    lastModified: d('2026-09-13'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/talk-to-someone-online`,     lastModified: d('2026-09-13'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/online-emotional-support`,   lastModified: d('2026-09-13'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/loneliness-support-online`,  lastModified: d('2026-09-13'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/someone-to-talk-to`,         lastModified: d('2026-09-13'), changeFrequency: 'weekly',  priority: 0.95 },
    // Round 14: NRI/diaspora geo-targeted pages — Canada, UK, USA (2026-09-14)
    { url: `${base}/punjabi-support-canada`,     lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-uk`,              lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/desi-support-usa`,           lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/nri-loneliness-canada`,      lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/nri-loneliness-uk`,          lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/talk-to-someone-hindi`,      lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    // Round 15: City-targeted & NRI marriage/dating/relationship pages (2026-09-14)
    // US cities
    { url: `${base}/indians-in-texas`,           lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-houston`,         lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-dallas`,          lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-atlanta`,         lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-new-jersey`,      lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-bay-area`,        lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-chicago`,         lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-seattle`,         lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-new-york`,        lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-florida`,         lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-boston`,          lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-phoenix`,         lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    // UK & Canada cities
    { url: `${base}/indians-in-birmingham`,      lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-leicester`,       lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-toronto`,         lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indians-in-vancouver`,       lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    // NRI marriage, dating, relationships
    { url: `${base}/nri-marriage-usa`,           lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/nri-marriage-uk`,            lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/nri-marriage-canada`,        lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/nri-dating-usa`,             lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/nri-dating-uk`,              lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/nri-long-distance-relationship`, lastModified: d('2026-09-14'), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/nri-relationship-problems`,  lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/arranged-marriage-nri`,      lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/nri-loneliness-usa`,         lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/second-generation-indian-usa`, lastModified: d('2026-09-14'), changeFrequency: 'weekly', priority: 0.95 },
    // NRI identity & emotional
    { url: `${base}/nri-homesick`,               lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/nri-identity-crisis`,        lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/nri-anxiety-abroad`,         lastModified: d('2026-09-14'), changeFrequency: 'weekly',  priority: 0.95 },
    { url: `${base}/indian-diaspora-mental-health`, lastModified: d('2026-09-14'), changeFrequency: 'weekly', priority: 0.95 },

    // Round 16: Singapore & Malaysia NRI pages (2026-09-14)
    { url: `${base}/singapore-loneliness`,            lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/singapore-relationship-advice`,   lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/singapore-rant`,                  lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/singapore-empathy-listener`,      lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/singapore-talk-to-someone`,       lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/malaysia-loneliness`,             lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/malaysia-relationship-advice`,    lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/malaysia-rant`,                   lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/malaysia-empathy-listener`,       lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/malaysia-talk-to-someone`,        lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },

    // Round 17: UAE, Dubai, Gulf & Middle East NRI pages (2026-09-14)
    { url: `${base}/uae-loneliness`,                  lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/uae-relationship-advice`,         lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/dubai-loneliness`,                lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/middle-east-rant`,                lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/middle-east-empathy-listener`,    lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/middle-east-loneliness`,          lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/kuwait-loneliness`,               lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/oman-loneliness`,                 lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/gulf-nri-support`,                lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/gulf-relationship-support`,       lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },

    // Round 18: UK NRI pages (2026-09-14)
    { url: `${base}/uk-loneliness`,                   lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/uk-relationship-advice`,          lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/uk-rant-to-someone`,              lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/uk-empathy-listener`,             lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/london-loneliness`,               lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/uk-mental-health-south-asian`,    lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/uk-nri-support`,                  lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/uk-talk-to-someone`,              lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/british-indian-support`,          lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/uk-winter-loneliness`,            lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },

    // Round 19: Canada NRI pages (2026-09-14)
    { url: `${base}/canada-loneliness`,               lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/canada-relationship-advice`,      lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/canada-rant-to-someone`,          lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/canada-empathy-listener`,         lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/toronto-loneliness`,              lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/canada-immigration-stress`,       lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/canada-nri-support`,              lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/canada-winter-loneliness`,        lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/canada-talk-to-someone`,          lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/desi-canada-support`,             lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },

    // Round 20: USA NRI pages (2026-09-14)
    { url: `${base}/usa-loneliness`,                  lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/usa-relationship-advice`,         lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/usa-rant-to-someone`,             lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/usa-empathy-listener`,            lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/indian-american-loneliness`,      lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/usa-h1b-visa-stress`,             lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/usa-nri-support`,                 lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/usa-talk-to-someone`,             lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/desi-usa-support`,                lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/usa-therapy-alternative`,         lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },

    // Round 21: Gulf gap-fill + Australia NRI + AEO AI-alternative (2026-09-15)
    { url: `${base}/kuwait-talk-to-someone`,          lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/kuwait-nri-support`,              lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/oman-talk-to-someone`,            lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/oman-nri-support`,                lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/uae-talk-to-someone`,             lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/australia-talk-to-someone`,       lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/australia-nri-support`,           lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    // AEO: AI chatbot alternative — country-specific (targets ChatGPT/Gemini/Perplexity users)
    { url: `${base}/ai-chatbot-alternative-uae`,      lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/ai-chatbot-alternative-uk`,       lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/ai-chatbot-alternative-singapore`,lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    { url: `${base}/ai-chatbot-alternative-malaysia`, lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.95 },
    // Round 21b: Real human vs AI — core AEO pages (2026-09-15)
    { url: `${base}/talk-to-real-person-not-ai`,          lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.98 },
    { url: `${base}/vent-to-a-real-person-online`,        lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.97 },
    { url: `${base}/relationship-support-real-person`,    lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.97 },
    { url: `${base}/emotional-support-without-ai`,        lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.97 },
    { url: `${base}/india-talk-to-real-person`,           lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.97 },
    { url: `${base}/india-vent-to-real-person`,           lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.97 },
    { url: `${base}/india-human-support-vs-ai`,           lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.97 },
    { url: `${base}/indian-american-real-support`,        lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.96 },
    { url: `${base}/usa-talk-to-real-person-support`,     lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.97 },
    { url: `${base}/usa-vent-real-person`,                lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.97 },
    { url: `${base}/uk-talk-to-real-person-support`,      lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.97 },
    { url: `${base}/uk-vent-real-person`,                 lastModified: d(TODAY), changeFrequency: 'weekly', priority: 0.97 },
  ]
}
