import type { Metadata } from 'next'

export const dynamic = 'force-static'

export const metadata: Metadata = {
  title: 'Talk to a Real Person Online in India | LeanOn',
  description: 'Looking for a real person to talk to online in India? LeanOn connects you with peer listeners for private one-to-one text or voice conversations. Start with one free 5-minute introduction.',
  keywords: [
    'talk to a real person online India',
    'real person to talk to online India',
    'talk to someone online India',
    'human listener online India',
    'someone to talk to online India',
    'real human conversation India',
    'human emotional support India',
    'peer support India',
    'talk to someone instead of AI India',
  ],
  alternates: {
    canonical: 'https://www.leanon.app/talk-to-real-person-online-india',
    languages: { 'en-IN': 'https://www.leanon.app/talk-to-real-person-online-india' },
  },
  openGraph: {
    title: 'Talk to a Real Person Online in India | LeanOn',
    description: 'A private one-to-one conversation with a real peer listener by text or voice. Start with one free 5-minute introduction.',
    url: 'https://www.leanon.app/talk-to-real-person-online-india',
    siteName: 'LeanOn',
    type: 'website',
  },
}

const faqs = [
  {
    q: 'How can I talk to a real person online in India?',
    a: 'Open LeanOn, browse available peer listeners, read their profiles and choose someone who feels relevant to what you want to talk about. You can start a one-to-one conversation by text or voice when a listener is available.',
  },
  {
    q: 'Is LeanOn a real person or an AI chatbot?',
    a: 'LeanOn connects you with real human peer listeners. The conversation is not generated by a chatbot. LeanOn is built for human-to-human peer support and everyday emotional connection.',
  },
  {
    q: 'Can I talk to someone without going to therapy?',
    a: 'Yes. LeanOn is peer support, not therapy or clinical treatment. You can use it when you want someone to listen about loneliness, relationships, work pressure, family situations, grief, overthinking or simply a difficult day. If you need clinical care, speak with an appropriately qualified mental-health professional.',
  },
  {
    q: 'Can I choose whether I use text or voice?',
    a: 'Yes. LeanOn supports both text and voice conversations. You can choose the format that feels more comfortable for the conversation.',
  },
  {
    q: 'Can I try LeanOn before paying?',
    a: 'New seekers get one free 5-minute introductory session. It is intended to help you find out whether a particular listener feels like a good fit before you continue with paid time.',
  },
  {
    q: 'How much does LeanOn cost?',
    a: 'There is one free 5-minute introductory session for new seekers. After that, pricing is based on the listener you choose and the time you use; the applicable rate is shown before you start a paid conversation.',
  },
  {
    q: 'Is LeanOn therapy or a crisis helpline?',
    a: 'No. LeanOn provides peer support and human connection, not therapy, diagnosis, medical treatment or crisis intervention. If you are in immediate danger or thinking about self-harm, contact an appropriate emergency or crisis service instead.',
  },
]

const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'WebPage',
      name: 'Talk to a Real Person Online in India',
      description: metadata.description,
      url: 'https://www.leanon.app/talk-to-real-person-online-india',
      isPartOf: { '@type': 'WebSite', name: 'LeanOn', url: 'https://www.leanon.app' },
      about: [
        { '@type': 'Thing', name: 'Peer support' },
        { '@type': 'Thing', name: 'Human connection' },
        { '@type': 'Thing', name: 'Online conversation' },
      ],
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'LeanOn', item: 'https://www.leanon.app' },
        { '@type': 'ListItem', position: 2, name: 'Talk to a Real Person Online in India', item: 'https://www.leanon.app/talk-to-real-person-online-india' },
      ],
    },
    {
      '@type': 'FAQPage',
      mainEntity: faqs.map((faq) => ({
        '@type': 'Question',
        name: faq.q,
        acceptedAnswer: { '@type': 'Answer', text: faq.a },
      })),
    },
  ],
}

const situations = [
  ['Loneliness', 'You have people around you but nobody you feel comfortable being completely honest with.'],
  ['Relationship stress', 'You want to talk through a relationship, marriage or breakup without involving people you know.'],
  ['Work pressure', 'Your job, career or business is taking up more emotional space than you can comfortably carry alone.'],
  ['Family pressure', 'You need a neutral person to listen before you decide what you want to do.'],
  ['Overthinking', 'You keep replaying the same situation and want to say it out loud to another person.'],
  ['A difficult day', 'Nothing has a neat label. You simply want another human being to listen for a while.'],
]

export default function TalkToRealPersonOnlineIndiaPage() {
  return (
    <main className="min-h-screen bg-white text-[#0F4867]">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      <div className="mx-auto max-w-5xl px-5 py-8 sm:px-8 sm:py-12">
        <nav className="mb-12 flex items-center justify-between" aria-label="Primary">
          <a href="/" className="text-2xl font-black tracking-tight">Lean<span className="text-[#1A8FA0]">On</span></a>
          <a href="/browse" className="rounded-full bg-[#1A8FA0] px-5 py-2.5 text-sm font-extrabold text-white">Browse listeners</a>
        </nav>

        <header className="max-w-4xl">
          <p className="mb-4 text-sm font-extrabold uppercase tracking-widest text-[#1A8FA0]">Human connection · India</p>
          <h1 className="mb-6 text-4xl font-black leading-tight sm:text-6xl">Talk to a Real Person Online in India</h1>
          <p className="mb-8 max-w-3xl text-lg leading-8 text-slate-600 sm:text-xl">Sometimes you are not looking for another article, another chatbot or another piece of advice. You want another human being to listen. LeanOn connects you with peer listeners for one-to-one conversations by text or voice.</p>
          <div className="flex flex-wrap gap-3">
            <a href="/browse" className="rounded-full bg-[#FF9933] px-7 py-3.5 font-extrabold text-white">Find someone to talk to →</a>
            <a href="/ai-human-support" className="rounded-full border border-[#D5EEF6] bg-[#F0F8FC] px-7 py-3.5 font-extrabold text-[#0F4867]">Human vs AI</a>
          </div>
        </header>

        <section className="mt-12 rounded-3xl border border-[#D5EEF6] bg-[#F0F8FC] p-7 sm:p-9">
          <h2 className="mb-4 text-2xl font-black">You do not need a crisis or a diagnosis to want someone to talk to</h2>
          <p className="leading-7 text-slate-600">A lot of searches for “someone to talk to” are not really about finding information. They are about finding a person who can listen without being a friend, family member, colleague or romantic partner.</p>
          <p className="mt-4 leading-7 text-slate-600">That is the space LeanOn is designed for. You choose a listener, start with one free 5-minute introduction, and decide whether you want to continue. There is no requirement to turn the conversation into therapy or to arrive with a perfectly defined problem.</p>
        </section>

        <section className="mt-10">
          <h2 className="mb-6 text-2xl font-black">What can you talk about?</h2>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {situations.map(([title, body]) => (
              <article key={title} className="rounded-2xl border border-slate-200 p-6">
                <h3 className="mb-2 text-lg font-black">{title}</h3>
                <p className="text-sm leading-7 text-slate-600">{body}</p>
              </article>
            ))}
          </div>
        </section>

        <section className="mt-10 rounded-3xl bg-[#0F4867] p-7 text-white sm:p-9">
          <h2 className="mb-5 text-2xl font-black">How talking to a real person on LeanOn works</h2>
          <ol className="space-y-5 text-white/90">
            <li><strong className="text-white">1. Browse listeners.</strong> Look at profiles, lived-experience topics, rates and availability.</li>
            <li><strong className="text-white">2. Start with 5 minutes free.</strong> New seekers get one free introductory session before deciding whether to continue.</li>
            <li><strong className="text-white">3. Choose text or voice.</strong> Use text when you want a quieter conversation or voice when hearing another person feels better.</li>
            <li><strong className="text-white">4. Continue only if it feels right.</strong> The listener's rate is shown before paid time begins. You can choose a different listener next time.</li>
          </ol>
          <a href="/browse" className="mt-7 inline-flex rounded-full bg-[#FF9933] px-7 py-3.5 font-extrabold text-white">Browse real listeners →</a>
        </section>

        <section className="mt-10">
          <h2 className="mb-6 text-2xl font-black">Real person vs AI: which conversation are you looking for?</h2>
          <div className="overflow-x-auto rounded-2xl border border-slate-200">
            <table className="w-full min-w-[640px] border-collapse text-left text-sm">
              <thead><tr className="bg-[#F0F8FC]"><th className="p-4 font-black">If you want…</th><th className="p-4 font-black">AI assistant</th><th className="p-4 font-black">LeanOn</th></tr></thead>
              <tbody>
                <tr className="border-t border-slate-200"><td className="p-4 font-bold">Information or brainstorming</td><td className="p-4">Often a good fit</td><td className="p-4">Not the primary purpose</td></tr>
                <tr className="border-t border-slate-200"><td className="p-4 font-bold">Another human being</td><td className="p-4">No</td><td className="p-4">Yes — a peer listener</td></tr>
                <tr className="border-t border-slate-200"><td className="p-4 font-bold">Someone to listen to a personal story</td><td className="p-4">AI conversation</td><td className="p-4">One-to-one human conversation</td></tr>
                <tr className="border-t border-slate-200"><td className="p-4 font-bold">Text or voice with a person</td><td className="p-4">Depends on the AI product</td><td className="p-4">Both are supported</td></tr>
              </tbody>
            </table>
          </div>
          <p className="mt-4 text-sm leading-7 text-slate-500">There is no need to choose one tool for every situation. AI can be useful for many things; LeanOn is specifically for people who want human connection and peer support.</p>
        </section>

        <section className="mt-10">
          <h2 className="mb-5 text-2xl font-black">Questions people ask</h2>
          <div className="divide-y divide-slate-200 rounded-2xl border border-slate-200 px-5">
            {faqs.map((faq) => (
              <details key={faq.q} className="py-5">
                <summary className="cursor-pointer font-extrabold">{faq.q}</summary>
                <p className="pt-3 leading-7 text-slate-600">{faq.a}</p>
              </details>
            ))}
          </div>
        </section>

        <section className="mt-10 grid gap-4 sm:grid-cols-2">
          <a href="/late-night-support-india" className="rounded-2xl border border-[#D5EEF6] bg-[#F0F8FC] p-6">
            <h2 className="font-black">Need someone late at night?</h2>
            <p className="mt-2 text-sm leading-6 text-slate-600">See the late-night support page and check live listener availability.</p>
          </a>
          <a href="/support/new-city-india" className="rounded-2xl border border-[#D5EEF6] bg-[#F0F8FC] p-6">
            <h2 className="font-black">Lonely after moving to a new city?</h2>
            <p className="mt-2 text-sm leading-6 text-slate-600">Explore support for relocation loneliness in India.</p>
          </a>
        </section>

        <section className="mt-10 rounded-3xl border border-[#D5EEF6] p-7 text-center sm:p-9">
          <h2 className="mb-3 text-2xl font-black">Want to talk to a real person?</h2>
          <p className="mb-6 text-slate-600">Start with one free 5-minute introduction and see whether the listener feels right for you.</p>
          <a href="/browse" className="inline-flex rounded-full bg-[#FF9933] px-7 py-3.5 font-extrabold text-white">Find a listener →</a>
        </section>

        <p className="mt-10 text-xs leading-6 text-slate-500">LeanOn provides peer support and human connection, not therapy, counselling, diagnosis or clinical treatment. If you are in immediate danger or experiencing an emergency, contact an appropriate local emergency or crisis service.</p>
      </div>
    </main>
  )
}
